# import = ["/Users/tianchengwang/src/dotfiles/alacritty/dracula.toml"]

[window]
# decorations: full
# decorations = "transparent"
# decorations = "buttonless"
decorations= "None"
# startup_mode="Fullscreen"
startup_mode="Maximized"
dynamic_padding=true
padding.x= 5
padding.y= 1
option_as_alt = "Both"
opacity = 0.85
blur = true
# position.x = 875
# position.y = 20
# dimensions.columns = 110
# dimensions.lines = 65

[font]
size= 12
# size: 17
offset.x= 0
offset.y= 2
# normal.family= "Hack"
# italic.style = "normal"


[shell]
program = "/opt/homebrew/bin/fish"
# use_thin_strokes= true
# defaults write -g AppleFontSmoothing -int 0
# https://github.com/alacritty/alacritty/issues/4616

[colors.primary]
  # Default colors
# background= '0x282c34'
background= '0x000000'
foreground= '0xabb2bf'


# background = "#000000"
# foreground = "#ffffff"
# bright_foreground = "#ffffff"


[colors.normal]
# green = "0x9fdd69"
# blue = "0x73C2FB"
# blue = "#89CFEF"
# white = "#ffffff"


# [[keyboard.bindings]]
# action = "ToggleMaximized"
# key = "F"
# mods = "Alt"
# test
