# import = ["/Users/tianchengwang/src/dotfiles/alacritty/dracula.toml"]

[window]
# decorations: full
# decorations = "transparent"
# decorations = "buttonless"
decorations= "None"
startup_mode="Fullscreen"
# startup_mode="Maximized"
dynamic_padding=true
padding.x= 5
padding.y= 1
option_as_alt= "Both"
opacity = 1
# blur = true
# position.x = 875
# position.y = 20
# dimensions.columns = 110
# dimensions.lines = 65

[font]
size= 13
# size: 17
offset.x= 0
offset.y= 2
normal.family= "Hack"


[shell]
program = "/opt/homebrew/bin/fish"
# use_thin_strokes= true
# defaults write -g AppleFontSmoothing -int 0
# https://github.com/alacritty/alacritty/issues/4616

[colors.normal]
#
green = "#9fdd69"
# white = "#ffffff"
# [colors.primary]
#
# background = "#000000"
# foreground = "#ffffff"
# bright_foreground = "#ffffff"


# [[keyboard.bindings]]
# action = "ToggleMaximized"
# key = "F"
# mods = "Alt"
# test
